name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - if: "startsWith(github.actor, 'h-beeen')"
        run: echo "REVIEWERS=wm-o, EunChanNam" >> $GITHUB_ENV
      - if: "startsWith(github.actor, 'wm-o')"
        run: echo "REVIEWERS=h-beeen, EunChanNam" >> $GITHUB_ENV
      - if: "startsWith(github.actor, 'EunChanNam')"
        run: echo "REVIEWERS=wm-o, h-beeen" >> $GITHUB_ENV
      - if: "startsWith(github.actor, 'SWARVY')"
        run: echo "REVIEWERS=rheefine, HyeonJeong519" >> $GITHUB_ENV
      - if: "startsWith(github.actor, 'HyeonJeong519')"
        run: echo "REVIEWERS=rheefine, SWARVY" >> $GITHUB_ENV
      - if: "startsWith(github.actor, 'rheefine')"
        run: echo "REVIEWERS=SWARVY, HyeonJeong519" >> $GITHUB_ENV
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ env.REVIEWERS }}
          ready-comment: '코드리뷰 대기 중 입니다 🙆 <reviewers>'
          merged-comment: '성공적으로 Merge 되었습니다. Reviewed By <reviewers> :wink:'
